# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/rpgd
pkgincludedir = $(includedir)/rpgd
pkglibdir = $(libdir)/rpgd
pkglibexecdir = $(libexecdir)/rpgd
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = rpgd$(EXEEXT) rpgclient$(EXEEXT) rpgweb$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_rpgclient_OBJECTS = rpgclient-arena.$(OBJEXT) \
	rpgclient-battle.$(OBJEXT) rpgclient-casino.$(OBJEXT) \
	rpgclient-dungeon.$(OBJEXT) rpgclient-editor.$(OBJEXT) \
	rpgclient-global.$(OBJEXT) rpgclient-lists.$(OBJEXT) \
	rpgclient-logon.$(OBJEXT) rpgclient-main.$(OBJEXT) \
	rpgclient-mainmenu.$(OBJEXT) rpgclient-naval.$(OBJEXT) \
	rpgclient-newuser.$(OBJEXT) rpgclient-party.$(OBJEXT) \
	rpgclient-square.$(OBJEXT) rpgclient-sysop.$(OBJEXT) \
	rpgclient-tavern.$(OBJEXT) rpgclient-term.$(OBJEXT) \
	rpgclient-common.$(OBJEXT)
rpgclient_OBJECTS = $(am_rpgclient_OBJECTS)
rpgclient_LDADD = $(LDADD)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
rpgclient_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(rpgclient_CFLAGS) \
	$(CFLAGS) $(rpgclient_LDFLAGS) $(LDFLAGS) -o $@
am_rpgd_OBJECTS = rpgd-btree.$(OBJEXT) rpgd-rpgd.$(OBJEXT) \
	rpgd-common.$(OBJEXT)
rpgd_OBJECTS = $(am_rpgd_OBJECTS)
rpgd_DEPENDENCIES =
rpgd_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(rpgd_CFLAGS) $(CFLAGS) \
	$(rpgd_LDFLAGS) $(LDFLAGS) -o $@
am_rpgweb_OBJECTS = rpgweb-main.$(OBJEXT) rpgweb-common.$(OBJEXT)
rpgweb_OBJECTS = $(am_rpgweb_OBJECTS)
rpgweb_LDADD = $(LDADD)
rpgweb_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(rpgweb_CFLAGS) $(CFLAGS) \
	$(rpgweb_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(rpgclient_SOURCES) $(rpgd_SOURCES) $(rpgweb_SOURCES)
DIST_SOURCES = $(rpgclient_SOURCES) $(rpgd_SOURCES) $(rpgweb_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in COPYING \
	ChangeLog README compile config.guess config.sub depcomp \
	install-sh ltmain.sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/rhurst/src/rpgd/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /home/rhurst/src/rpgd/missing autoconf
AUTOHEADER = ${SHELL} /home/rhurst/src/rpgd/missing autoheader
AUTOMAKE = ${SHELL} /home/rhurst/src/rpgd/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = 
MAKEINFO = ${SHELL} /home/rhurst/src/rpgd/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = rpgd
PACKAGE_BUGREPORT = http://robert.hurst-ri.us/games/rpgd/
PACKAGE_NAME = rpgd
PACKAGE_STRING = rpgd 2.5.4
PACKAGE_TARNAME = rpgd
PACKAGE_URL = 
PACKAGE_VERSION = 2.5.4
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 2.5.4
abs_builddir = /home/rhurst/src/rpgd
abs_srcdir = /home/rhurst/src/rpgd
abs_top_builddir = /home/rhurst/src/rpgd
abs_top_srcdir = /home/rhurst/src/rpgd
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/rhurst/src/rpgd/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = \
	-I m4

AM_CPPFLAGS = \
	-DPACKAGE_DATA_DIR=\""$(datadir)"\" 

AM_CFLAGS = \
	 -Werror

rpgweb_SOURCES = \
	src/rpgweb/main.c\
	src/common.c

rpgweb_LDFLAGS = \
	-lm

rpgweb_CFLAGS = \
	-Iinclude

rpgclient_SOURCES = \
	src/rpgclient/arena.c\
	src/rpgclient/battle.c \
	src/rpgclient/casino.c \
	src/rpgclient/dungeon.c \
	src/rpgclient/editor.c \
	src/rpgclient/global.c \
	src/rpgclient/lists.c \
	src/rpgclient/logon.c \
	src/rpgclient/main.c \
	src/rpgclient/mainmenu.c \
	src/rpgclient/naval.c \
	src/rpgclient/newuser.c \
	src/rpgclient/party.c \
	src/rpgclient/square.c \
	src/rpgclient/sysop.c \
	src/rpgclient/tavern.c \
	src/rpgclient/term.c \
	src/common.c

rpgclient_LDFLAGS = \
	-lm

rpgclient_CFLAGS = \
	-Iinclude

rpgd_SOURCES = \
	src/rpgd/btree.c\
	src/rpgd/rpgd.c \
	src/common.c

rpgd_CFLAGS = \
	-Iinclude

rpgd_LDFLAGS = 
rpgd_LDADD = 
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

rpgclient$(EXEEXT): $(rpgclient_OBJECTS) $(rpgclient_DEPENDENCIES) $(EXTRA_rpgclient_DEPENDENCIES) 
	@rm -f rpgclient$(EXEEXT)
	$(AM_V_CCLD)$(rpgclient_LINK) $(rpgclient_OBJECTS) $(rpgclient_LDADD) $(LIBS)

rpgd$(EXEEXT): $(rpgd_OBJECTS) $(rpgd_DEPENDENCIES) $(EXTRA_rpgd_DEPENDENCIES) 
	@rm -f rpgd$(EXEEXT)
	$(AM_V_CCLD)$(rpgd_LINK) $(rpgd_OBJECTS) $(rpgd_LDADD) $(LIBS)

rpgweb$(EXEEXT): $(rpgweb_OBJECTS) $(rpgweb_DEPENDENCIES) $(EXTRA_rpgweb_DEPENDENCIES) 
	@rm -f rpgweb$(EXEEXT)
	$(AM_V_CCLD)$(rpgweb_LINK) $(rpgweb_OBJECTS) $(rpgweb_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/rpgclient-arena.Po
include ./$(DEPDIR)/rpgclient-battle.Po
include ./$(DEPDIR)/rpgclient-casino.Po
include ./$(DEPDIR)/rpgclient-common.Po
include ./$(DEPDIR)/rpgclient-dungeon.Po
include ./$(DEPDIR)/rpgclient-editor.Po
include ./$(DEPDIR)/rpgclient-global.Po
include ./$(DEPDIR)/rpgclient-lists.Po
include ./$(DEPDIR)/rpgclient-logon.Po
include ./$(DEPDIR)/rpgclient-main.Po
include ./$(DEPDIR)/rpgclient-mainmenu.Po
include ./$(DEPDIR)/rpgclient-naval.Po
include ./$(DEPDIR)/rpgclient-newuser.Po
include ./$(DEPDIR)/rpgclient-party.Po
include ./$(DEPDIR)/rpgclient-square.Po
include ./$(DEPDIR)/rpgclient-sysop.Po
include ./$(DEPDIR)/rpgclient-tavern.Po
include ./$(DEPDIR)/rpgclient-term.Po
include ./$(DEPDIR)/rpgd-btree.Po
include ./$(DEPDIR)/rpgd-common.Po
include ./$(DEPDIR)/rpgd-rpgd.Po
include ./$(DEPDIR)/rpgweb-common.Po
include ./$(DEPDIR)/rpgweb-main.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

rpgclient-arena.o: src/rpgclient/arena.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-arena.o -MD -MP -MF $(DEPDIR)/rpgclient-arena.Tpo -c -o rpgclient-arena.o `test -f 'src/rpgclient/arena.c' || echo '$(srcdir)/'`src/rpgclient/arena.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-arena.Tpo $(DEPDIR)/rpgclient-arena.Po
#	$(AM_V_CC)source='src/rpgclient/arena.c' object='rpgclient-arena.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-arena.o `test -f 'src/rpgclient/arena.c' || echo '$(srcdir)/'`src/rpgclient/arena.c

rpgclient-arena.obj: src/rpgclient/arena.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-arena.obj -MD -MP -MF $(DEPDIR)/rpgclient-arena.Tpo -c -o rpgclient-arena.obj `if test -f 'src/rpgclient/arena.c'; then $(CYGPATH_W) 'src/rpgclient/arena.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/arena.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-arena.Tpo $(DEPDIR)/rpgclient-arena.Po
#	$(AM_V_CC)source='src/rpgclient/arena.c' object='rpgclient-arena.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-arena.obj `if test -f 'src/rpgclient/arena.c'; then $(CYGPATH_W) 'src/rpgclient/arena.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/arena.c'; fi`

rpgclient-battle.o: src/rpgclient/battle.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-battle.o -MD -MP -MF $(DEPDIR)/rpgclient-battle.Tpo -c -o rpgclient-battle.o `test -f 'src/rpgclient/battle.c' || echo '$(srcdir)/'`src/rpgclient/battle.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-battle.Tpo $(DEPDIR)/rpgclient-battle.Po
#	$(AM_V_CC)source='src/rpgclient/battle.c' object='rpgclient-battle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-battle.o `test -f 'src/rpgclient/battle.c' || echo '$(srcdir)/'`src/rpgclient/battle.c

rpgclient-battle.obj: src/rpgclient/battle.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-battle.obj -MD -MP -MF $(DEPDIR)/rpgclient-battle.Tpo -c -o rpgclient-battle.obj `if test -f 'src/rpgclient/battle.c'; then $(CYGPATH_W) 'src/rpgclient/battle.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/battle.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-battle.Tpo $(DEPDIR)/rpgclient-battle.Po
#	$(AM_V_CC)source='src/rpgclient/battle.c' object='rpgclient-battle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-battle.obj `if test -f 'src/rpgclient/battle.c'; then $(CYGPATH_W) 'src/rpgclient/battle.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/battle.c'; fi`

rpgclient-casino.o: src/rpgclient/casino.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-casino.o -MD -MP -MF $(DEPDIR)/rpgclient-casino.Tpo -c -o rpgclient-casino.o `test -f 'src/rpgclient/casino.c' || echo '$(srcdir)/'`src/rpgclient/casino.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-casino.Tpo $(DEPDIR)/rpgclient-casino.Po
#	$(AM_V_CC)source='src/rpgclient/casino.c' object='rpgclient-casino.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-casino.o `test -f 'src/rpgclient/casino.c' || echo '$(srcdir)/'`src/rpgclient/casino.c

rpgclient-casino.obj: src/rpgclient/casino.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-casino.obj -MD -MP -MF $(DEPDIR)/rpgclient-casino.Tpo -c -o rpgclient-casino.obj `if test -f 'src/rpgclient/casino.c'; then $(CYGPATH_W) 'src/rpgclient/casino.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/casino.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-casino.Tpo $(DEPDIR)/rpgclient-casino.Po
#	$(AM_V_CC)source='src/rpgclient/casino.c' object='rpgclient-casino.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-casino.obj `if test -f 'src/rpgclient/casino.c'; then $(CYGPATH_W) 'src/rpgclient/casino.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/casino.c'; fi`

rpgclient-dungeon.o: src/rpgclient/dungeon.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-dungeon.o -MD -MP -MF $(DEPDIR)/rpgclient-dungeon.Tpo -c -o rpgclient-dungeon.o `test -f 'src/rpgclient/dungeon.c' || echo '$(srcdir)/'`src/rpgclient/dungeon.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-dungeon.Tpo $(DEPDIR)/rpgclient-dungeon.Po
#	$(AM_V_CC)source='src/rpgclient/dungeon.c' object='rpgclient-dungeon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-dungeon.o `test -f 'src/rpgclient/dungeon.c' || echo '$(srcdir)/'`src/rpgclient/dungeon.c

rpgclient-dungeon.obj: src/rpgclient/dungeon.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-dungeon.obj -MD -MP -MF $(DEPDIR)/rpgclient-dungeon.Tpo -c -o rpgclient-dungeon.obj `if test -f 'src/rpgclient/dungeon.c'; then $(CYGPATH_W) 'src/rpgclient/dungeon.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/dungeon.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-dungeon.Tpo $(DEPDIR)/rpgclient-dungeon.Po
#	$(AM_V_CC)source='src/rpgclient/dungeon.c' object='rpgclient-dungeon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-dungeon.obj `if test -f 'src/rpgclient/dungeon.c'; then $(CYGPATH_W) 'src/rpgclient/dungeon.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/dungeon.c'; fi`

rpgclient-editor.o: src/rpgclient/editor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-editor.o -MD -MP -MF $(DEPDIR)/rpgclient-editor.Tpo -c -o rpgclient-editor.o `test -f 'src/rpgclient/editor.c' || echo '$(srcdir)/'`src/rpgclient/editor.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-editor.Tpo $(DEPDIR)/rpgclient-editor.Po
#	$(AM_V_CC)source='src/rpgclient/editor.c' object='rpgclient-editor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-editor.o `test -f 'src/rpgclient/editor.c' || echo '$(srcdir)/'`src/rpgclient/editor.c

rpgclient-editor.obj: src/rpgclient/editor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-editor.obj -MD -MP -MF $(DEPDIR)/rpgclient-editor.Tpo -c -o rpgclient-editor.obj `if test -f 'src/rpgclient/editor.c'; then $(CYGPATH_W) 'src/rpgclient/editor.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/editor.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-editor.Tpo $(DEPDIR)/rpgclient-editor.Po
#	$(AM_V_CC)source='src/rpgclient/editor.c' object='rpgclient-editor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-editor.obj `if test -f 'src/rpgclient/editor.c'; then $(CYGPATH_W) 'src/rpgclient/editor.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/editor.c'; fi`

rpgclient-global.o: src/rpgclient/global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-global.o -MD -MP -MF $(DEPDIR)/rpgclient-global.Tpo -c -o rpgclient-global.o `test -f 'src/rpgclient/global.c' || echo '$(srcdir)/'`src/rpgclient/global.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-global.Tpo $(DEPDIR)/rpgclient-global.Po
#	$(AM_V_CC)source='src/rpgclient/global.c' object='rpgclient-global.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-global.o `test -f 'src/rpgclient/global.c' || echo '$(srcdir)/'`src/rpgclient/global.c

rpgclient-global.obj: src/rpgclient/global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-global.obj -MD -MP -MF $(DEPDIR)/rpgclient-global.Tpo -c -o rpgclient-global.obj `if test -f 'src/rpgclient/global.c'; then $(CYGPATH_W) 'src/rpgclient/global.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/global.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-global.Tpo $(DEPDIR)/rpgclient-global.Po
#	$(AM_V_CC)source='src/rpgclient/global.c' object='rpgclient-global.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-global.obj `if test -f 'src/rpgclient/global.c'; then $(CYGPATH_W) 'src/rpgclient/global.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/global.c'; fi`

rpgclient-lists.o: src/rpgclient/lists.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-lists.o -MD -MP -MF $(DEPDIR)/rpgclient-lists.Tpo -c -o rpgclient-lists.o `test -f 'src/rpgclient/lists.c' || echo '$(srcdir)/'`src/rpgclient/lists.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-lists.Tpo $(DEPDIR)/rpgclient-lists.Po
#	$(AM_V_CC)source='src/rpgclient/lists.c' object='rpgclient-lists.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-lists.o `test -f 'src/rpgclient/lists.c' || echo '$(srcdir)/'`src/rpgclient/lists.c

rpgclient-lists.obj: src/rpgclient/lists.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-lists.obj -MD -MP -MF $(DEPDIR)/rpgclient-lists.Tpo -c -o rpgclient-lists.obj `if test -f 'src/rpgclient/lists.c'; then $(CYGPATH_W) 'src/rpgclient/lists.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/lists.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-lists.Tpo $(DEPDIR)/rpgclient-lists.Po
#	$(AM_V_CC)source='src/rpgclient/lists.c' object='rpgclient-lists.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-lists.obj `if test -f 'src/rpgclient/lists.c'; then $(CYGPATH_W) 'src/rpgclient/lists.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/lists.c'; fi`

rpgclient-logon.o: src/rpgclient/logon.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-logon.o -MD -MP -MF $(DEPDIR)/rpgclient-logon.Tpo -c -o rpgclient-logon.o `test -f 'src/rpgclient/logon.c' || echo '$(srcdir)/'`src/rpgclient/logon.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-logon.Tpo $(DEPDIR)/rpgclient-logon.Po
#	$(AM_V_CC)source='src/rpgclient/logon.c' object='rpgclient-logon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-logon.o `test -f 'src/rpgclient/logon.c' || echo '$(srcdir)/'`src/rpgclient/logon.c

rpgclient-logon.obj: src/rpgclient/logon.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-logon.obj -MD -MP -MF $(DEPDIR)/rpgclient-logon.Tpo -c -o rpgclient-logon.obj `if test -f 'src/rpgclient/logon.c'; then $(CYGPATH_W) 'src/rpgclient/logon.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/logon.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-logon.Tpo $(DEPDIR)/rpgclient-logon.Po
#	$(AM_V_CC)source='src/rpgclient/logon.c' object='rpgclient-logon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-logon.obj `if test -f 'src/rpgclient/logon.c'; then $(CYGPATH_W) 'src/rpgclient/logon.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/logon.c'; fi`

rpgclient-main.o: src/rpgclient/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-main.o -MD -MP -MF $(DEPDIR)/rpgclient-main.Tpo -c -o rpgclient-main.o `test -f 'src/rpgclient/main.c' || echo '$(srcdir)/'`src/rpgclient/main.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-main.Tpo $(DEPDIR)/rpgclient-main.Po
#	$(AM_V_CC)source='src/rpgclient/main.c' object='rpgclient-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-main.o `test -f 'src/rpgclient/main.c' || echo '$(srcdir)/'`src/rpgclient/main.c

rpgclient-main.obj: src/rpgclient/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-main.obj -MD -MP -MF $(DEPDIR)/rpgclient-main.Tpo -c -o rpgclient-main.obj `if test -f 'src/rpgclient/main.c'; then $(CYGPATH_W) 'src/rpgclient/main.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/main.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-main.Tpo $(DEPDIR)/rpgclient-main.Po
#	$(AM_V_CC)source='src/rpgclient/main.c' object='rpgclient-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-main.obj `if test -f 'src/rpgclient/main.c'; then $(CYGPATH_W) 'src/rpgclient/main.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/main.c'; fi`

rpgclient-mainmenu.o: src/rpgclient/mainmenu.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-mainmenu.o -MD -MP -MF $(DEPDIR)/rpgclient-mainmenu.Tpo -c -o rpgclient-mainmenu.o `test -f 'src/rpgclient/mainmenu.c' || echo '$(srcdir)/'`src/rpgclient/mainmenu.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-mainmenu.Tpo $(DEPDIR)/rpgclient-mainmenu.Po
#	$(AM_V_CC)source='src/rpgclient/mainmenu.c' object='rpgclient-mainmenu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-mainmenu.o `test -f 'src/rpgclient/mainmenu.c' || echo '$(srcdir)/'`src/rpgclient/mainmenu.c

rpgclient-mainmenu.obj: src/rpgclient/mainmenu.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-mainmenu.obj -MD -MP -MF $(DEPDIR)/rpgclient-mainmenu.Tpo -c -o rpgclient-mainmenu.obj `if test -f 'src/rpgclient/mainmenu.c'; then $(CYGPATH_W) 'src/rpgclient/mainmenu.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/mainmenu.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-mainmenu.Tpo $(DEPDIR)/rpgclient-mainmenu.Po
#	$(AM_V_CC)source='src/rpgclient/mainmenu.c' object='rpgclient-mainmenu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-mainmenu.obj `if test -f 'src/rpgclient/mainmenu.c'; then $(CYGPATH_W) 'src/rpgclient/mainmenu.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/mainmenu.c'; fi`

rpgclient-naval.o: src/rpgclient/naval.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-naval.o -MD -MP -MF $(DEPDIR)/rpgclient-naval.Tpo -c -o rpgclient-naval.o `test -f 'src/rpgclient/naval.c' || echo '$(srcdir)/'`src/rpgclient/naval.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-naval.Tpo $(DEPDIR)/rpgclient-naval.Po
#	$(AM_V_CC)source='src/rpgclient/naval.c' object='rpgclient-naval.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-naval.o `test -f 'src/rpgclient/naval.c' || echo '$(srcdir)/'`src/rpgclient/naval.c

rpgclient-naval.obj: src/rpgclient/naval.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-naval.obj -MD -MP -MF $(DEPDIR)/rpgclient-naval.Tpo -c -o rpgclient-naval.obj `if test -f 'src/rpgclient/naval.c'; then $(CYGPATH_W) 'src/rpgclient/naval.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/naval.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-naval.Tpo $(DEPDIR)/rpgclient-naval.Po
#	$(AM_V_CC)source='src/rpgclient/naval.c' object='rpgclient-naval.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-naval.obj `if test -f 'src/rpgclient/naval.c'; then $(CYGPATH_W) 'src/rpgclient/naval.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/naval.c'; fi`

rpgclient-newuser.o: src/rpgclient/newuser.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-newuser.o -MD -MP -MF $(DEPDIR)/rpgclient-newuser.Tpo -c -o rpgclient-newuser.o `test -f 'src/rpgclient/newuser.c' || echo '$(srcdir)/'`src/rpgclient/newuser.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-newuser.Tpo $(DEPDIR)/rpgclient-newuser.Po
#	$(AM_V_CC)source='src/rpgclient/newuser.c' object='rpgclient-newuser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-newuser.o `test -f 'src/rpgclient/newuser.c' || echo '$(srcdir)/'`src/rpgclient/newuser.c

rpgclient-newuser.obj: src/rpgclient/newuser.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-newuser.obj -MD -MP -MF $(DEPDIR)/rpgclient-newuser.Tpo -c -o rpgclient-newuser.obj `if test -f 'src/rpgclient/newuser.c'; then $(CYGPATH_W) 'src/rpgclient/newuser.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/newuser.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-newuser.Tpo $(DEPDIR)/rpgclient-newuser.Po
#	$(AM_V_CC)source='src/rpgclient/newuser.c' object='rpgclient-newuser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-newuser.obj `if test -f 'src/rpgclient/newuser.c'; then $(CYGPATH_W) 'src/rpgclient/newuser.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/newuser.c'; fi`

rpgclient-party.o: src/rpgclient/party.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-party.o -MD -MP -MF $(DEPDIR)/rpgclient-party.Tpo -c -o rpgclient-party.o `test -f 'src/rpgclient/party.c' || echo '$(srcdir)/'`src/rpgclient/party.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-party.Tpo $(DEPDIR)/rpgclient-party.Po
#	$(AM_V_CC)source='src/rpgclient/party.c' object='rpgclient-party.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-party.o `test -f 'src/rpgclient/party.c' || echo '$(srcdir)/'`src/rpgclient/party.c

rpgclient-party.obj: src/rpgclient/party.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-party.obj -MD -MP -MF $(DEPDIR)/rpgclient-party.Tpo -c -o rpgclient-party.obj `if test -f 'src/rpgclient/party.c'; then $(CYGPATH_W) 'src/rpgclient/party.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/party.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-party.Tpo $(DEPDIR)/rpgclient-party.Po
#	$(AM_V_CC)source='src/rpgclient/party.c' object='rpgclient-party.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-party.obj `if test -f 'src/rpgclient/party.c'; then $(CYGPATH_W) 'src/rpgclient/party.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/party.c'; fi`

rpgclient-square.o: src/rpgclient/square.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-square.o -MD -MP -MF $(DEPDIR)/rpgclient-square.Tpo -c -o rpgclient-square.o `test -f 'src/rpgclient/square.c' || echo '$(srcdir)/'`src/rpgclient/square.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-square.Tpo $(DEPDIR)/rpgclient-square.Po
#	$(AM_V_CC)source='src/rpgclient/square.c' object='rpgclient-square.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-square.o `test -f 'src/rpgclient/square.c' || echo '$(srcdir)/'`src/rpgclient/square.c

rpgclient-square.obj: src/rpgclient/square.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-square.obj -MD -MP -MF $(DEPDIR)/rpgclient-square.Tpo -c -o rpgclient-square.obj `if test -f 'src/rpgclient/square.c'; then $(CYGPATH_W) 'src/rpgclient/square.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/square.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-square.Tpo $(DEPDIR)/rpgclient-square.Po
#	$(AM_V_CC)source='src/rpgclient/square.c' object='rpgclient-square.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-square.obj `if test -f 'src/rpgclient/square.c'; then $(CYGPATH_W) 'src/rpgclient/square.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/square.c'; fi`

rpgclient-sysop.o: src/rpgclient/sysop.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-sysop.o -MD -MP -MF $(DEPDIR)/rpgclient-sysop.Tpo -c -o rpgclient-sysop.o `test -f 'src/rpgclient/sysop.c' || echo '$(srcdir)/'`src/rpgclient/sysop.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-sysop.Tpo $(DEPDIR)/rpgclient-sysop.Po
#	$(AM_V_CC)source='src/rpgclient/sysop.c' object='rpgclient-sysop.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-sysop.o `test -f 'src/rpgclient/sysop.c' || echo '$(srcdir)/'`src/rpgclient/sysop.c

rpgclient-sysop.obj: src/rpgclient/sysop.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-sysop.obj -MD -MP -MF $(DEPDIR)/rpgclient-sysop.Tpo -c -o rpgclient-sysop.obj `if test -f 'src/rpgclient/sysop.c'; then $(CYGPATH_W) 'src/rpgclient/sysop.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/sysop.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-sysop.Tpo $(DEPDIR)/rpgclient-sysop.Po
#	$(AM_V_CC)source='src/rpgclient/sysop.c' object='rpgclient-sysop.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-sysop.obj `if test -f 'src/rpgclient/sysop.c'; then $(CYGPATH_W) 'src/rpgclient/sysop.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/sysop.c'; fi`

rpgclient-tavern.o: src/rpgclient/tavern.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-tavern.o -MD -MP -MF $(DEPDIR)/rpgclient-tavern.Tpo -c -o rpgclient-tavern.o `test -f 'src/rpgclient/tavern.c' || echo '$(srcdir)/'`src/rpgclient/tavern.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-tavern.Tpo $(DEPDIR)/rpgclient-tavern.Po
#	$(AM_V_CC)source='src/rpgclient/tavern.c' object='rpgclient-tavern.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-tavern.o `test -f 'src/rpgclient/tavern.c' || echo '$(srcdir)/'`src/rpgclient/tavern.c

rpgclient-tavern.obj: src/rpgclient/tavern.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-tavern.obj -MD -MP -MF $(DEPDIR)/rpgclient-tavern.Tpo -c -o rpgclient-tavern.obj `if test -f 'src/rpgclient/tavern.c'; then $(CYGPATH_W) 'src/rpgclient/tavern.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/tavern.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-tavern.Tpo $(DEPDIR)/rpgclient-tavern.Po
#	$(AM_V_CC)source='src/rpgclient/tavern.c' object='rpgclient-tavern.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-tavern.obj `if test -f 'src/rpgclient/tavern.c'; then $(CYGPATH_W) 'src/rpgclient/tavern.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/tavern.c'; fi`

rpgclient-term.o: src/rpgclient/term.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-term.o -MD -MP -MF $(DEPDIR)/rpgclient-term.Tpo -c -o rpgclient-term.o `test -f 'src/rpgclient/term.c' || echo '$(srcdir)/'`src/rpgclient/term.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-term.Tpo $(DEPDIR)/rpgclient-term.Po
#	$(AM_V_CC)source='src/rpgclient/term.c' object='rpgclient-term.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-term.o `test -f 'src/rpgclient/term.c' || echo '$(srcdir)/'`src/rpgclient/term.c

rpgclient-term.obj: src/rpgclient/term.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-term.obj -MD -MP -MF $(DEPDIR)/rpgclient-term.Tpo -c -o rpgclient-term.obj `if test -f 'src/rpgclient/term.c'; then $(CYGPATH_W) 'src/rpgclient/term.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/term.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-term.Tpo $(DEPDIR)/rpgclient-term.Po
#	$(AM_V_CC)source='src/rpgclient/term.c' object='rpgclient-term.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-term.obj `if test -f 'src/rpgclient/term.c'; then $(CYGPATH_W) 'src/rpgclient/term.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgclient/term.c'; fi`

rpgclient-common.o: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-common.o -MD -MP -MF $(DEPDIR)/rpgclient-common.Tpo -c -o rpgclient-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-common.Tpo $(DEPDIR)/rpgclient-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgclient-common.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c

rpgclient-common.obj: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -MT rpgclient-common.obj -MD -MP -MF $(DEPDIR)/rpgclient-common.Tpo -c -o rpgclient-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgclient-common.Tpo $(DEPDIR)/rpgclient-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgclient-common.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgclient_CFLAGS) $(CFLAGS) -c -o rpgclient-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`

rpgd-btree.o: src/rpgd/btree.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-btree.o -MD -MP -MF $(DEPDIR)/rpgd-btree.Tpo -c -o rpgd-btree.o `test -f 'src/rpgd/btree.c' || echo '$(srcdir)/'`src/rpgd/btree.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-btree.Tpo $(DEPDIR)/rpgd-btree.Po
#	$(AM_V_CC)source='src/rpgd/btree.c' object='rpgd-btree.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-btree.o `test -f 'src/rpgd/btree.c' || echo '$(srcdir)/'`src/rpgd/btree.c

rpgd-btree.obj: src/rpgd/btree.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-btree.obj -MD -MP -MF $(DEPDIR)/rpgd-btree.Tpo -c -o rpgd-btree.obj `if test -f 'src/rpgd/btree.c'; then $(CYGPATH_W) 'src/rpgd/btree.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgd/btree.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-btree.Tpo $(DEPDIR)/rpgd-btree.Po
#	$(AM_V_CC)source='src/rpgd/btree.c' object='rpgd-btree.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-btree.obj `if test -f 'src/rpgd/btree.c'; then $(CYGPATH_W) 'src/rpgd/btree.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgd/btree.c'; fi`

rpgd-rpgd.o: src/rpgd/rpgd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-rpgd.o -MD -MP -MF $(DEPDIR)/rpgd-rpgd.Tpo -c -o rpgd-rpgd.o `test -f 'src/rpgd/rpgd.c' || echo '$(srcdir)/'`src/rpgd/rpgd.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-rpgd.Tpo $(DEPDIR)/rpgd-rpgd.Po
#	$(AM_V_CC)source='src/rpgd/rpgd.c' object='rpgd-rpgd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-rpgd.o `test -f 'src/rpgd/rpgd.c' || echo '$(srcdir)/'`src/rpgd/rpgd.c

rpgd-rpgd.obj: src/rpgd/rpgd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-rpgd.obj -MD -MP -MF $(DEPDIR)/rpgd-rpgd.Tpo -c -o rpgd-rpgd.obj `if test -f 'src/rpgd/rpgd.c'; then $(CYGPATH_W) 'src/rpgd/rpgd.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgd/rpgd.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-rpgd.Tpo $(DEPDIR)/rpgd-rpgd.Po
#	$(AM_V_CC)source='src/rpgd/rpgd.c' object='rpgd-rpgd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-rpgd.obj `if test -f 'src/rpgd/rpgd.c'; then $(CYGPATH_W) 'src/rpgd/rpgd.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgd/rpgd.c'; fi`

rpgd-common.o: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-common.o -MD -MP -MF $(DEPDIR)/rpgd-common.Tpo -c -o rpgd-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-common.Tpo $(DEPDIR)/rpgd-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgd-common.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c

rpgd-common.obj: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -MT rpgd-common.obj -MD -MP -MF $(DEPDIR)/rpgd-common.Tpo -c -o rpgd-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgd-common.Tpo $(DEPDIR)/rpgd-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgd-common.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgd_CFLAGS) $(CFLAGS) -c -o rpgd-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`

rpgweb-main.o: src/rpgweb/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -MT rpgweb-main.o -MD -MP -MF $(DEPDIR)/rpgweb-main.Tpo -c -o rpgweb-main.o `test -f 'src/rpgweb/main.c' || echo '$(srcdir)/'`src/rpgweb/main.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgweb-main.Tpo $(DEPDIR)/rpgweb-main.Po
#	$(AM_V_CC)source='src/rpgweb/main.c' object='rpgweb-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -c -o rpgweb-main.o `test -f 'src/rpgweb/main.c' || echo '$(srcdir)/'`src/rpgweb/main.c

rpgweb-main.obj: src/rpgweb/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -MT rpgweb-main.obj -MD -MP -MF $(DEPDIR)/rpgweb-main.Tpo -c -o rpgweb-main.obj `if test -f 'src/rpgweb/main.c'; then $(CYGPATH_W) 'src/rpgweb/main.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgweb/main.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgweb-main.Tpo $(DEPDIR)/rpgweb-main.Po
#	$(AM_V_CC)source='src/rpgweb/main.c' object='rpgweb-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -c -o rpgweb-main.obj `if test -f 'src/rpgweb/main.c'; then $(CYGPATH_W) 'src/rpgweb/main.c'; else $(CYGPATH_W) '$(srcdir)/src/rpgweb/main.c'; fi`

rpgweb-common.o: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -MT rpgweb-common.o -MD -MP -MF $(DEPDIR)/rpgweb-common.Tpo -c -o rpgweb-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgweb-common.Tpo $(DEPDIR)/rpgweb-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgweb-common.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -c -o rpgweb-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c

rpgweb-common.obj: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -MT rpgweb-common.obj -MD -MP -MF $(DEPDIR)/rpgweb-common.Tpo -c -o rpgweb-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpgweb-common.Tpo $(DEPDIR)/rpgweb-common.Po
#	$(AM_V_CC)source='src/common.c' object='rpgweb-common.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rpgweb_CFLAGS) $(CFLAGS) -c -o rpgweb-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic clean-libtool \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
